apiVersion: v1
kind: Pod
metadata:
  name: dp-client
spec:
  nodeSelector:
    dennis: "4"
  hostname: dp-client
  containers:
  - image: busybox
    imagePullPolicy: Always
    name: dp-client
    command: [ "sleep", "999999" ]
