apiVersion: v1
kind: Service
metadata:
  name: dp-srv1
spec:
  ports:
  - name: webserver
    port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    app: dp-server

---
apiVersion: v1
kind: Pod
metadata:
  name: dp-server
  labels:
    app: dp-server
spec:
  nodeSelector:
    dennis: "4"
  hostname: dp-server
  containers:
  - image: busybox
    imagePullPolicy: Always
    name: dp-server
    command: [ "sleep", "999999" ]
